version: "3"
networks:
  kong-net:
    driver: bridge
  kongNetwork:
    name: kong-net
    external: true

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kongNetwork
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka-kafka-1
    networks:
      - kongNetwork
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-kafka-1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kong-database-kafka:
    image: postgres:13
    networks:
      - kongNetwork
    restart: always
    container_name: kong-database-kafka
    environment:
    - POSTGRES_USER=kong
    - POSTGRES_DB=kongEnterprise
    - POSTGRES_PASSWORD=kongpass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  kong-ent-bootstrap:
    image: kong/kong-gateway:arm64-3.1.1.3-alpine
    networks:
      - kongNetwork
    container_name: kong-ent-bootstrap
    hostname: kongBootstrap
    restart: on-failure
    command: "kong migrations bootstrap"
    environment:
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_PLUGINS=bundled
    - KONG_PASSWORD=kongpass
    - KONG_AUDIT_LOG=on
    - KONG_LOG_LEVEL=debug
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database-kafka
    - KONG_PG_DATABASE=kongEnterprise
    - KONG_PG_USER=kong
    - KONG_PG_PASSWORD=kongpass
    depends_on:
      - kong-database-kafka
  kong-gateway-kafka:
    image: kong/kong-gateway:arm64-3.1.1.3-alpine
    networks:
      - kongNetwork
    ports:
    - 8000:8000
    - 8001:8001
    - 8002:8002
    - 8003:8003
    - 8004:8004
    - 8005:8005
    - 8006:8006
    - 8443:8443
    - 8444:8444
    - 8445:8445
    container_name: kong-gateway-kafka
    hostname: konggatewaykafka
    mem_limit: 1500m
    restart: always
    environment:
    - KONG_LICENSE_DATA=${KONG_LICENSE_DATA}
    - KONG_PLUGINS=bundled,kafka-consumer
    - KONG_PASSWORD=kongpass
    - KONG_AUDIT_LOG=on
    - KONG_DATABASE=postgres
    - KONG_PG_HOST=kong-database-kafka
    - KONG_PG_DATABASE=kongEnterprise
    - KONG_PG_USER=kong
    - KONG_PG_PASSWORD=kongpass
    - KONG_PROXY_ACCESS_LOG=/dev/stdout
    - KONG_ADMIN_ACCESS_LOG=/dev/stdout
    - KONG_PROXY_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_ERROR_LOG=/dev/stderr
    - KONG_ADMIN_LISTEN=0.0.0.0:8001
    - KONG_ADMIN_GUI_URL=http://localhost:8002
    volumes:
    # Push the 'kafka-consumer' custom plugin
    - ./kong/plugins/kafka-consumer:/usr/local/share/lua/5.1/kong/plugins/kafka-consumer
    # Update the Resty Kafka library from version 0.14 to 0.20 and push the Consumer library
    - ./resty/kafka:/usr/local/share/lua/5.1/resty/kafka
    depends_on:
      - kong-database-kafka
      - kong-ent-bootstrap